name: CI + Auto Merge to Main + Deploy

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm install
      - name: Test
        run: npm test --if-present
      - name: Build
        run: npm run build
      - name: Build Docker
        run: docker build -t next-app .

  auto-merge:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          UPDATE_LABELS: ""
          MERGE_LABELS: ""

  deploy:
    needs: auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
