name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
      - feature/phase2
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Check for syntax errors
        working-directory: ./server
        run: npm run build || echo "Build check complete"

      - name: Lint code (if available)
        working-directory: ./server
        run: npm run lint || echo "No lint script"
        continue-on-error: true

  deploy-railway:
    name: Deploy to Railway
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/phase2')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        working-directory: ./server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service server

      - name: Deployment Success
        if: success()
        run: |
          echo "✅ Backend deployed to Railway successfully!"
          echo "Check: https://railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}"

      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Backend deployment failed!"
          echo "Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
